### ISSUE TITLE
Filter based on class inheritance

### ISSUE THREAD

**Issue by yi2020** [mkdocstrings/pytkdocs#106]
**Is your feature request related to a problem? Please describe.**
I'm documenting a package but I only care about classes of certain types. Specifically, those that inherit (directly, or indirectly) from a specific class (we call the top-level one Mergeable). I don't want to document the other classes.

**Describe the solution you'd like**
A filter that is class based. Ideally, we can expand the filters to take more factors into account, like if something is a dataclass.

**Describe alternatives you've considered**
I tried using the name-based filter, but it's not a fit for this.

**Comment by pawamoy** [comment]
Hello @yi2020, very sorry for the late answer :bow: 

I'm working on a new tool to replace pytkdocs (which is very limited by design). This new tool will make it easy to write extensions. An extension that can be configured to prune objects (like classes that do not inherit  from a Mergeable class) is something that will be possible to write :slightly_smiling_face: 

Stay tuned!

**Comment by pawamoy** [comment]
Late update but the new tool is Griffe and it supports [extensions](https://mkdocstrings.github.io/griffe/guide/users/extending/). Let me know if the docs are enough for you to write an extension that covers your use-case :slightly_smiling_face:
